# Generated by Django 4.2.1 on 2023-05-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_city_created"),
    ]

    operations = [
        migrations.AlterModelOptions(name="city", options={"ordering": ("created",)},),
    ]
